/*
 * Created on 2026-07-07 ( Time 23:14:25 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wdyapplications.prime_access.dao.entity;

import java.io.Serializable;


import java.math.BigDecimal;
import java.util.Date;
import com.wdyapplications.prime_access.dao.entity.*;
import jakarta.persistence.*;
import lombok.Data;

/**
 * Persistent class for entity stored in table "mouvement"
 *
 * @author Telosys Tools Generator
 *
 */

@Data
@Entity
@Table(name="mouvement" )
public class Mouvement implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    // test value Integer
        private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="type_mouvement", length=255)
    private String     typeMouvement ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deleted_at")
    private Date       deletedAt    ;

    @Column(name="is_deleted")
    private Boolean    isDeleted    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;

    @Column(name="status_id")
    private Integer    statusId     ;

    @Column(name="latitude")
    private BigDecimal latitude     ;

    @Column(name="longitude")
    private BigDecimal longitude    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="validation_date")
    private Date       validationDate ;

	// "personnelId" (column "personnel_id") is not defined by itself because used as FK in a link 
	// "salleId" (column "salle_id") is not defined by itself because used as FK in a link 
	// "agentSecuriteId" (column "agent_securite_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="personnel_id", referencedColumnName="id")
    private Personnel personnel2  ;
    @ManyToOne
    @JoinColumn(name="salle_id", referencedColumnName="id")
    private Salle salle       ;
    @ManyToOne
    @JoinColumn(name="agent_securite_id", referencedColumnName="id")
    private Personnel personnel   ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Mouvement() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
