spring.datasource.url=jdbc:postgresql://localhost:5432/prime_access?allowPublicKeyRetrieval=true&useSSL=false&sessionVariables=sql_mode=""
spring.datasource.postgres.username=postgres
spring.datasource.postgres.password=DorgelesDB@2024
spring.datasource.username=postgres
spring.datasource.password=DorgelesDB@2024
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.postgres.driverClassName=org.postgresql.Driver
spring.datasource.postgres.hikari.registerMbeans=true
spring.jpa.hibernate.ddl-auto=update

#Minio config
spring.minio.url=https://minio.wdyapplications.com/minio
spring.minio.bucket=pharm-app
spring.minio.access-key=JypSzH5xykz5QMtB8oOK
spring.minio.secret-key=QhSgcIUzgyVs2FJFVXVLJFJlWMtCsYJxk4VuWjyG